'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import dynamic from "next/dynamic";

import { useState } from "react";
import Header from "./components/common/module/header";
import { parseCookies } from "nookies";
import DashHeader from "./components/common/module/dash-header";


const ReduxProvider = dynamic(() => import("@/redux/redux-provider"), {
  ssr: false
});

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="mt-100">
          <ReduxProvider>
            {/* 조건이 참일 때 뒤에 요소 렌더링 */}
            {parseCookies().message === "SUCCESS" && <Header />}
           
            {children}
          </ReduxProvider>
        </div>
      </body>
    </html>
  );
}